# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Gitclone\Tengee\ui_files\card.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_card(object):
    def setupUi(self, card):
        card.setObjectName("card")
        card.resize(1288, 200)
        card.setMinimumSize(QtCore.QSize(0, 200))
        card.setMaximumSize(QtCore.QSize(16777215, 250))
        card.setStyleSheet("QPushButton {\n"
"    height: 28px;\n"
"    border: transparent;\n"
"    border-radius: 8px;\n"
"    background: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255,255,255);\n"
"    background: #c09054;\n"
"    border: transparent;\n"
"}")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(card)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cardframe = QtWidgets.QFrame(card)
        self.cardframe.setStyleSheet("#cardframe {\n"
"    border-radius: 15px;\n"
"    background: rgba(203, 191, 187, 80);\n"
"}")
        self.cardframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardframe.setObjectName("cardframe")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.cardframe)
        self.horizontalLayout_5.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cardimg = QtWidgets.QFrame(self.cardframe)
        self.cardimg.setMinimumSize(QtCore.QSize(280, 180))
        self.cardimg.setMaximumSize(QtCore.QSize(280, 180))
        self.cardimg.setAutoFillBackground(False)
        self.cardimg.setStyleSheet("image: url(:/icons/background-login.png);\n"
"border-radius: 10px;\n"
"padding: -50px;")
        self.cardimg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardimg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardimg.setObjectName("cardimg")
        self.horizontalLayout_5.addWidget(self.cardimg)
        self.cardbody = QtWidgets.QFrame(self.cardframe)
        self.cardbody.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cardbody.setStyleSheet("")
        self.cardbody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cardbody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cardbody.setObjectName("cardbody")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.cardbody)
        self.verticalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleframe = QtWidgets.QFrame(self.cardbody)
        self.titleframe.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titleframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleframe.setObjectName("titleframe")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.titleframe)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.title = QtWidgets.QLabel(self.titleframe)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("")
        self.title.setScaledContents(False)
        self.title.setWordWrap(False)
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title)
        self.ellipse = QtWidgets.QLabel(self.titleframe)
        self.ellipse.setObjectName("ellipse")
        self.horizontalLayout_3.addWidget(self.ellipse)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.titleframe)
        self.author = QtWidgets.QLabel(self.cardbody)
        self.author.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.author.setFont(font)
        self.author.setStyleSheet("#author {\n"
"    color: gray;\n"
"}")
        self.author.setWordWrap(True)
        self.author.setObjectName("author")
        self.verticalLayout_2.addWidget(self.author)
        self.description = QtWidgets.QLabel(self.cardbody)
        self.description.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.description.setFont(font)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout_2.addWidget(self.description)
        self.frame = QtWidgets.QFrame(self.cardbody)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.price = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.horizontalLayout_2.addWidget(self.price)
        self.oldprice = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(True)
        self.oldprice.setFont(font)
        self.oldprice.setObjectName("oldprice")
        self.horizontalLayout_2.addWidget(self.oldprice)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.cardbody)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enroll_btn = QtWidgets.QPushButton(self.frame_2)
        self.enroll_btn.setMinimumSize(QtCore.QSize(200, 40))
        self.enroll_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.enroll_btn.setFont(font)
        self.enroll_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enroll_btn.setObjectName("enroll_btn")
        self.horizontalLayout.addWidget(self.enroll_btn)
        self.addtocard_btn = QtWidgets.QPushButton(self.frame_2)
        self.addtocard_btn.setMinimumSize(QtCore.QSize(40, 40))
        self.addtocard_btn.setMaximumSize(QtCore.QSize(40, 40))
        self.addtocard_btn.setStyleSheet("image: url(:/icons/shopping-cart.png);\n"
"padding: 6px;")
        self.addtocard_btn.setText("")
        self.addtocard_btn.setObjectName("addtocard_btn")
        self.horizontalLayout.addWidget(self.addtocard_btn)
        spacerItem2 = QtWidgets.QSpacerItem(698, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_5.addWidget(self.cardbody)
        self.horizontalLayout_4.addWidget(self.cardframe)

        self.retranslateUi(card)
        QtCore.QMetaObject.connectSlotsByName(card)

    def retranslateUi(self, card):
        _translate = QtCore.QCoreApplication.translate
        card.setWindowTitle(_translate("card", "Form"))
        self.title.setText(_translate("card", "Courses Title here"))
        self.ellipse.setText(_translate("card", "..."))
        self.author.setText(_translate("card", "Author name here"))
        self.description.setText(_translate("card", "Description here"))
        self.price.setText(_translate("card", "₫ Tuition fee here"))
        self.oldprice.setText(_translate("card", "₫ Old tuition fee here"))
        self.enroll_btn.setText(_translate("card", "Enroll now"))
import resource_rc
